Repository kubernetes-sigs/release-notes, pull requests merged in 2019-06, with the labels that each got.

#37 Move backend to dedicated location
  .gitignore
  Makefile
  cmd/server/main.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#39 Toss in quick 1.15 draft for @castrojo
  src/assets/data/release-notes.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#42 Substitute console.log with logger implementation
  src/app/notes/notes.effects.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#43 Fix release version filtering
  src/app/notes/notes.component.html
  src/app/notes/notes.effects.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#34 Add bootstrap to package.json
  angular.json
  package-lock.json
  package.json
  src/app/app.component.css
  src/app/app.component.ts
  src/app/notes/notes.component.scss
  src/app/notes/notes.component.ts
  src/app/options/options.component.css
  src/app/options/options.component.ts
  src/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#47 Fix CSS style and fit heading
  src/app/notes/notes.component.scss
  src/styles.css
Labels: approved, cncf-cla: yes, lgtm, size/S

#46 Update path based on url/filter
  src/app/notes/notes.component.ts
  src/app/notes/notes.effects.ts
  src/app/options/options.component.spec.ts
  src/app/options/options.component.ts
  src/app/shared/model/options.model.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#45 Add support for new JSON format
  src/app/notes/notes.effects.ts
  src/app/notes/notes.model.ts
  src/app/notes/notes.service.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#49 Add options model unit tests and fix lint
  src/app/shared/model/options.model.spec.ts
  src/app/shared/model/options.model.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#50 Remove backend implementation
  Makefile
  cmd/server/main.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#51 Add preview badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#52 Add modal component and cleanup navbar
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/modal/modal.component.html
  src/app/modal/modal.component.ts
  src/app/options/options.component.html
  src/app/options/options.component.spec.ts
  src/app/options/options.component.ts
  src/styles.css
Labels: approved, cncf-cla: yes, lgtm, size/L

#53 Update ngrx dependencies to Angular 8
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#55 Change site title to 'Kubernetes Release Notes'
  cypress/integration/app.spec.ts
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/index.html
Labels: cncf-cla: yes, size/S

#56 Update notes to latest branch-ff
  src/app/notes/notes.effects.ts
  src/assets/data/release-notes.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#57 Add 'about' text
  src/app/modal/modal.component.html
  src/app/options/options.component.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#58 Update "About" modal
  src/app/options/options.component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#60 Fix navbar width
  src/app/options/options.component.html
  src/styles.css
Labels: approved, cncf-cla: yes, lgtm, size/S

#54 Update version to 1.0.0
  README.md
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#63 Tag entries with the dot release
  src/assets/data/release-notes.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#64 Fix filtering logic
  src/app/notes/notes.effects.ts
  src/app/shared/model/options.model.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#65 Fix releaseVersion filter, added filter helper functions
  src/app/notes/notes.effects.ts
  src/app/options/options.component.spec.ts
  src/app/options/options.component.ts
  src/app/shared/model/options.model.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#68 Fix width issue for small content cards
  src/app/options/options.component.html
  src/styles.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#66 Remove unused Filter from GetNotes()
  src/app/notes/notes.actions.spec.ts
  src/app/notes/notes.actions.ts
  src/app/notes/notes.component.ts
  src/app/notes/notes.effects.spec.ts
  src/app/notes/notes.effects.ts
  src/app/notes/notes.service.spec.ts
  src/app/notes/notes.service.ts
  src/assets/.gitkeep
Labels: approved, cncf-cla: yes, lgtm, size/S

#67 Add e2e test suite
  angular.json
  cypress/app.po.ts
  cypress/integration/app.spec.ts
  cypress/tsconfig.json
  package.json
  src/app/modal/modal.component.html
  src/app/notes/notes.service.ts
  src/app/options/options.component.html
  src/app/options/options.component.spec.ts
  src/app/options/options.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/testdata/release-notes.json
Labels: approved, cncf-cla: yes, lgtm, size/L
