Repository kubernetes-sigs/release-notes, pull requests merged in 2019-10, with the labels that each got.

#108 Sort filter options regarding its logic
  src/app/shared/model/options.model.spec.ts
  src/app/shared/model/options.model.ts
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#117 Add Sascha as an approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#111 added 1.17 pre-releases to filter
  src/app/shared/model/filter.model.spec.ts
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#113 Add v1.15.5 release notes
  src/assets/release-notes-1.15.5.json
  src/environments/assets.ts
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#114 Add v1.16.1/2 release notes
  src/assets/release-notes-1.16.1.json
  src/assets/release-notes-1.16.2.json
  src/environments/assets.ts
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#101 Sanitize doc descriptions
  src/app/notes/notes.component.html
  src/app/notes/notes.component.spec.ts
  src/app/notes/notes.component.ts
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#115 Show error message of notes parsing/retrieval fails
  src/app/notes/notes.component.html
  src/app/notes/notes.component.ts
  src/app/notes/notes.effects.ts
  src/app/notes/notes.reducer.ts
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#109 Sort assets to show latest notes first
  src/environments/assets.ts
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#110 Fix text size zoom for mobile devices
  src/app/main/main.component.scss
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#118 Adding release notes for 1.17.0 alpha 2 and 3.
  src/assets/release-notes-1.17.0-alpha.2.json
  src/assets/release-notes-1.17.0-alpha.3.json
  src/environments/assets.ts
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XXL
