Repository kubernetes-sigs/release-notes, pull requests merged in 2019-05, with the labels that each got.

#18 Add jest for unit testing
  .gitignore
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/notes/notes.component.spec.ts
  src/app/notes/notes.service.spec.ts
  src/app/notes/notes.service.ts
  src/app/options/options.component.spec.ts
  src/app/options/options.service.spec.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/karma.conf.js
  src/main.ts
  src/setupJest.ts
  src/test.ts
  src/tsconfig.app.json
  src/tsconfig.spec.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#20 Add cypress for end-to-end testing
  .gitignore
  angular.json
  cypress.json
  cypress/app.po.ts
  cypress/integration/app.spec.ts
  cypress/plugins/index.js
  cypress/tsconfig.json
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/tsconfig.e2e.json
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#26 Update package targets and fix lints
  .gitignore
  .prettierignore
  cypress/integration/app.spec.ts
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#21 Update filter and options types to be more typesafe
  src/app/notes/notes.actions.ts
  src/app/notes/notes.component.ts
  src/app/notes/notes.effects.ts
  src/app/notes/notes.service.ts
  src/app/options/options.component.ts
  src/app/options/options.model.ts
  src/app/options/options.service.ts
  src/app/shared/model/options.model.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#27 Add missing unit tests
  package-lock.json
  package.json
  src/app/notes/notes.actions.spec.ts
  src/app/notes/notes.component.spec.ts
  src/app/notes/notes.component.ts
  src/app/notes/notes.effects.spec.ts
  src/app/notes/notes.model.mock.ts
  src/app/notes/notes.reducer.spec.ts
  src/app/notes/notes.service.spec.ts
  src/app/options/options.component.spec.ts
  src/app/options/options.service.spec.ts
  src/app/shared/services/logger.service.spec.ts
  src/app/shared/services/logger.service.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#28 Add base netlify config
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#29 Fix unit-tests for new filter model
  package-lock.json
  src/app/notes/notes.actions.spec.ts
  src/app/notes/notes.component.spec.ts
  src/app/notes/notes.effects.spec.ts
  src/app/notes/notes.service.spec.ts
  src/app/options/options.component.spec.ts
Labels: approved, cncf-cla: yes, lgtm, size/M
