Repository kubernetes-sigs/release-notes, pull requests merged in 2019-07, with the labels that each got.

#69 Update to Angular 8.1
  angular.json
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#70 Add Google Analytics code
  src/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#71 Fix overall font-size
  src/styles.css
Labels: approved, cncf-cla: yes, lgtm, size/XS

#75 Add notes for Kubernetes 1.16.0-alpha.1
  src/app/notes/notes.effects.ts
  src/app/notes/notes.model.ts
  src/app/notes/notes.service.spec.ts
  src/app/notes/notes.service.ts
  src/assets/data/release-notes-1.15.json
  src/assets/data/release-notes-1.16.json
  src/environments/environment.prod.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#74 Update dependencies and fix popper.js include
  angular.json
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#78 Move assets from `data` to `assets` folder
  src/assets/release-notes-1.15.json
  src/assets/release-notes-1.16.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#79 Update site with 1.15.1 patch notes
  src/assets/release-notes-1.15.1.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#76 Add 'additional documentation' section
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/notes/notes.component.html
  src/app/notes/notes.component.scss
  src/app/notes/notes.component.spec.ts
  src/app/notes/notes.component.ts
  src/app/notes/notes.model.mock.ts
  src/app/notes/notes.model.ts
  src/app/options/options.component.spec.ts
  src/testdata/release-notes.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#81 Add additional documentation end-to-end tests
  cypress/integration/app.spec.ts
  src/app/notes/notes.component.html
  src/testdata/release-notes.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#85 Update release notes to 1.16.0-alpha.2
  src/assets/release-notes-1.16.json
Labels: approved, cncf-cla: yes, lgtm, size/XL
