Repository kubernetes-sigs/release-notes, pull requests merged in 2022-09, with the labels that each got.

#318 Issue of broken link is fixed
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test, sig/release

#320 Sync owners with k/release
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/M, approved, sig/release

#319 Add dependabot config file
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, size/S, approved, sig/release

#347 update bootstrap to 5.2.1
  .prettierrc.yml
  package-lock.json
  package.json
  src/app/filter/filter.component.html
  src/app/main/main.component.html
  src/app/modal/modal.component.html
  src/app/notes/notes.component.html
  src/app/settings/settings.component.html
  src/styles.css
Labels: cncf-cla: yes, lgtm, approved, ok-to-test, size/XXL, sig/release

#361 Patch relnotes.k8s.io to release v1.26.0-alpha.1
  src/assets/release-notes-1.26.0-alpha.1.json
  src/environments/assets.ts
Labels: cncf-cla: yes, lgtm, size/XL, approved, sig/release
